version: '2'
services:
  db:
    image: mysql:5.7.19
    volumes:
      - /opt/docker-data/hass/ha_mysql:/var/lib/mysql
    {{- if (.Values.MYSQL_PORT) }}
    ports:
      - ${MYSQL_PORT}:3306
    {{- end }}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  homeassistant:
    depends_on:
      - db
    image: homeassistant/home-assistant:0.60
    privileged: ${privileged}
    stdin_open: true
    network_mode: host
    volumes:
      - /opt/docker-data/hass:/config
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - ${HA_PORT}:8123
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
